# The Makefile to use the publication template
# running `> make` will run the default behavior:
# 	This will convert all markdown files that have a
# 	two-digit prefix >= 10 into latex source code and 
# 	then compile all those into a pdf. It will then
# 	add a bibliography to the publication, delete
# 	superfluous files and display the pdf using SumatraPDF.

# these specify the names of the .tex source files
MAIN = main
SRC = ./tex/$(MAIN)
BIB_PATH = ./references/bibliography.bib

ifeq ($(OS),Windows_NT)
	DEL = del
	DISPLAY = .\src\display_pdf.bat $(MAIN)
else
	DEL = rm -f
	DISPLAY = echo "no display update"
endif


# CC specifies the Latex compiler BIB specifies the 
# bibliography compiler
CC = pdflatex
BIB = bibtex



.PHONY : wbib nobib clean clean-meta pdf bib display

all:
ifneq (,$(wildcard $(BIB_PATH)))
all: wbib
else 
all: nobib
endif

# this is the default function, runs each function in the order below
wbib: md pdf bib rerun clean-meta display

# same as all but skips bibliography generation
nobib: md pdf rerun clean-meta display

# converts the markdown content into latex source code
md:
	python ./src/convert_to_tex.py

# Compiles latex to a pdf without bibliography
pdf:
	$(CC) $(SRC).tex
	
# adds the bibliography to the compiled pdf
bib:
	$(BIB) $(MAIN)

rerun:
	$(CC) $(SRC).tex
	$(CC) $(SRC).tex

# dynamically updates the pdf file using Sumatra pdf
display:
	$(DISPLAY)

# deletes all latex compilation meta data except log files for debugging
clean-meta:
	$(DEL) *.dvi
	$(DEL) *.aux
	$(DEL) *.bbl
	$(DEL) *.blg
	$(DEL) *.brf
	$(DEL) *.out
	$(DEL) *.toc
	$(DEL) *.run.xml
	$(DEL) *blx.bib

# cleans all files generated by this Makefile
clean:
	$(DEL) *.pdf
	$(DEL) *.log
	$(DEL) *.dvi
	$(DEL) *.aux
	$(DEL) *.bbl
	$(DEL) *.blg
	$(DEL) *.brf
	$(DEL) *.out
	$(DEL) *.toc
	$(DEL) *.bcf
	$(DEL) *.run.xml
	$(DEL) *blx.bib
	$(DEL) .\tex\section*
